import type { LucideIcon } from "lucide-react";
import {
  ArrowLeftRight,
  BarChart3,
  ChartLine,
  CircleDollarSign,
  Cog,
  Drill,
  HandCoins,
  Landmark,
  Lock,
  Tractor,
  UserCog,
  UserPlus,
  FileText,
  Files,
  FolderKanban,
  Forklift,
  Fuel,
  FileStack,
  Receipt,
  FileBarChart,
  LayoutDashboard,
  Package,
  ShoppingCart,
  Store,
  PackageCheck,
  Truck,
  Users,
  UsersRound,
  Wallet,
  Warehouse,
  Wrench,
} from "lucide-react";
import type { AdminSection } from "@/components/admin/AdminSidebar";

/** Lucide icons aligned with barane_invest_admin.html (Tabler equivalents). */
export const ADMIN_SECTION_ICON: Record<AdminSection, LucideIcon> = {
  dashboard: LayoutDashboard,
  builder: FileText,
  "builder-devis": FileText,
  "builder-bon-commande": ShoppingCart,
  "builder-facture": Receipt,
  "builder-bon-livraison": PackageCheck,
  saved: Files,
  customers: Users,
  suppliers: Store,
  products: Package,
  projets: FolderKanban,
  etats: FileBarChart,
  pv: FileText,
  rapports: FileBarChart,
  depots: Warehouse,
  engins: Tractor,
  personnel: UserCog,
  stock: Wrench,
  traitements: ArrowLeftRight,
  "purchase-requests": ShoppingCart,
  fuel: Fuel,
  "fuel-consommation": ChartLine,
  "fuel-stock": Warehouse,
  "fuel-bons": FileStack,
  "fuel-commande": ShoppingCart,
  "finance-caisse": Wallet,
  "finance-banque": Landmark,
  "finance-tresorerie": CircleDollarSign,
  "finance-clients": HandCoins,
  "finance-fournisseurs": Store,
  "finance-factures": Receipt,
  "finance-depenses": Receipt,
  "finance-clotures": Lock,
  "finance-etats": BarChart3,
  drilling: Drill,
  production: ChartLine,
  parts: Cog,
  logistics: Truck,
  "equipment-rental": Forklift,
  "rental-materials": Forklift,
  "rental-bons": FileStack,
  hr: UsersRound,
  utilisateurs: UserPlus,
};
