import type { LucideIcon } from "lucide-react";
import {
  ChartLine,
  Cog,
  Drill,
  Tractor,
  UserCog,
  UserPlus,
  FileText,
  Files,
  FolderKanban,
  Forklift,
  Fuel,
  ClipboardList,
  FileStack,
  Receipt,
  Gauge,
  LayoutDashboard,
  PenLine,
  Package,
  ShoppingCart,
  Store,
  PackageCheck,
  Truck,
  Users,
  UsersRound,
  Warehouse,
  Wrench,
} from "lucide-react";
import type { AdminSection } from "@/components/admin/AdminSidebar";

/** Lucide icons aligned with barane_invest_admin.html (Tabler equivalents). */
export const ADMIN_SECTION_ICON: Record<AdminSection, LucideIcon> = {
  dashboard: LayoutDashboard,
  builder: FileText,
  "builder-devis": FileText,
  "builder-bon-commande": ShoppingCart,
  "builder-facture": Receipt,
  "builder-bon-livraison": PackageCheck,
  saved: Files,
  customers: Users,
  suppliers: Store,
  products: Package,
  projets: FolderKanban,
  depots: Warehouse,
  engins: Tractor,
  personnel: UserCog,
  stock: Wrench,
  "purchase-requests": ShoppingCart,
  fuel: Fuel,
  "fuel-journal": ClipboardList,
  "fuel-stock": Warehouse,
  "fuel-bons": FileStack,
  "fuel-da-gasoil": ShoppingCart,
  "fuel-stats": Gauge,
  "fuel-saisie": PenLine,
  drilling: Drill,
  production: ChartLine,
  parts: Cog,
  logistics: Truck,
  "equipment-rental": Forklift,
  "rental-materials": Forklift,
  "rental-bons": FileStack,
  hr: UsersRound,
  utilisateurs: UserPlus,
};
